on:
  push:
    tags:
      - v*
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: 'Check env'
      env:
        BUILD_ENV: "${{ contains(github.ref, 'alpha') && 'dev' || 'prod' }}"
      run: |
        echo "${{ env.BUILD_ENV }}"
        echo "${{ github.ref }}"
        
